### ISSUE TITLE
Support Cross chain and Extensions

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/py-tokenlists#20]
Two test cases currently are failing that were added to Uniswap's repo:
https://github.com/Uniswap/token-lists/blob/main/test/schema/example-crosschain.tokenlist.json
https://github.com/Uniswap/token-lists/blob/main/test/schema/extensions-valid-object.tokenlist.json

**Comment by fubuloubu** [comment]
See: https://github.com/fubuloubu/py-tokenlists/runs/4835408461?check_suite_focus=true

**Comment by antazoey** [comment]
I'm not sure this was fully resolved.

A. There are absolutely no docs how to use this in a multi-chain example, I am so lost.

B. (this could be an issue in Ape framework): When I am connected to Optimism and I try to get a token, I still get a key error. But perhaps I am lacking information that could be solved from item A.

**Comment by antazoey** [comment]
Re-closing, most of issue is on not understanding lists as well as just having really limited lists out there... But some mult-chain docs would still be appreciated.

If anyone is looking to see how to work with multi-chain, see this repo: https://github.com/ApeWorX/ape-tokens
