### ISSUE TITLE
ValidationError on object-typed extension schema - nested level extensions do not work

### ISSUE THREAD

**Issue by antazoey** [ApeWorX/py-tokenlists#22]
### Environment information

* Python Version: 3.9.7
* OS: macOS

Latest.

As per this PR: https://github.com/Uniswap/token-lists/commit/74d8910fcbe618f3de6d5c7f0ec14ad774cf5d2a,
object schemas are now supported in the schema for extensions.

However, when trying to use them, the package fails with a pydantic validation error: `Incorrect extension field value: {...}`

You will notice the tests fail for this reason too.

### How can it be fixed?

Probably the best way is to build another model for the new extension schema and include the model in the Union of supported types.

**Comment by fubuloubu** [comment]
see #20

**Comment by antazoey** [comment]
Ah! closing because of duplicate
